"""change conection id to uuid

Revision ID: 161c2fbe5211
Revises: ff9e578f7c90
Create Date: 2025-07-15 17:07:57.223342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '161c2fbe5211'
down_revision: Union[str, Sequence[str], None] = 'ff9e578f7c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connection', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connection', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
