"""add connection name

Revision ID: 37926f21a756
Revises: 69b7870d8ac9
Create Date: 2025-07-04 14:14:24.227505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37926f21a756'
down_revision: Union[str, Sequence[str], None] = '69b7870d8ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('connection_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'connection_name')
    # ### end Alembic commands ###
