"""init

Revision ID: 58608d98ccec
Revises: 
Create Date: 2025-07-01 18:52:07.889162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58608d98ccec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(length=255), nullable=False),
    sa.Column('database_type', sa.String(length=255), nullable=False),
    sa.Column('database_url', sa.String(length=255), nullable=True),
    sa.Column('database_username', sa.String(length=255), nullable=False),
    sa.Column('database_password', sa.String(length=255), nullable=False),
    sa.Column('database_port', sa.Integer(), nullable=True),
    sa.Column('database_host', sa.String(length=255), nullable=True),
    sa.Column('database_table', sa.String(length=255), nullable=False),
    sa.Column('reg_user_id', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_id'), 'connection', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_id'), table_name='connection')
    op.drop_table('connection')
    # ### end Alembic commands ###
