"""add is_active

Revision ID: 69b7870d8ac9
Revises: 58608d98ccec
Create Date: 2025-07-01 19:10:12.978326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b7870d8ac9'
down_revision: Union[str, Sequence[str], None] = '58608d98ccec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'is_active')
    # ### end Alembic commands ###
