"""add mod_date

Revision ID: bf681552f76c
Revises: 37926f21a756
Create Date: 2025-07-10 17:41:11.994634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf681552f76c'
down_revision: Union[str, Sequence[str], None] = '37926f21a756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('mod_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'mod_date')
    # ### end Alembic commands ###
