version: "3.9"

services:
  auth_service:
    image: queryme/auth_service:latest
    container_name: auth_service
    ports:
      - "8081:8080"
    environment:
      - PROFILE=prod
      - TZ=Asia/Seoul
    depends_on:
      - mariadb
    networks:
      - backend

  connection_service:
    image: queryme/connection_service:latest
    container_name: connection_service  
    ports:
      - "8082:8080"
    environment:
      - PROFILE=prod
      - TZ=Asia/Seoul
    depends_on:
      - mariadb
    networks:
      - backend

  ddl_session_service:
    image: queryme/ddl_session_service:latest
    container_name: ddl_session_service
    ports:
      - "8084:8080"
    environment:
      - PROFILE=prod
      - TZ=Asia/Seoul
    depends_on:
      - mariadb
    networks:
      - backend

  history_service:
    image: queryme/history_service:latest
    container_name: history_service
    ports:
      - "8085:8080"
    environment:
      - PROFILE=prod
      - TZ=Asia/Seoul
    depends_on:
      - mariadb
    networks:
      - backend

  nl2sql_service:
    image: queryme/nl2sql_service:latest
    container_name: nl2sql_service
    ports:
      - "8083:8080"
    environment:
      - PROFILE=prod
      - TZ=Asia/Seoul
    depends_on:
      - mariadb
    networks:
      - backend

  gateway:
    image: queryme/gateway:latest
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - PROFILE=prod
      - TZ=Asia/Seoul
    depends_on:
      - auth_service
      - connection_service
      - ddl_session_service
      - history_service
      - nl2sql_service
    networks:
      - backend

  frontend:
    image: queryme/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - PROFILE=prod
      - TZ=Asia/Seoul
    networks:
      - frontend
      - backend

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=queryme
      - MYSQL_USER=queryme
      - MYSQL_PASSWORD=queryme1!
      - TZ=Asia/Seoul
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  frontend:
  backend: