"""init

Revision ID: 7e85bae9f196
Revises: 
Create Date: 2025-07-17 15:39:09.020640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e85bae9f196'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ddl_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_title', sa.String(length=255), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.Column('reg_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ddl_session_id'), 'ddl_session', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ddl_session_id'), table_name='ddl_session')
    op.drop_table('ddl_session')
    # ### end Alembic commands ###
