"""add end date and duration

Revision ID: 169cfe7f2cf5
Revises: 4fe16e04174c
Create Date: 2025-07-17 17:37:40.926622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169cfe7f2cf5'
down_revision: Union[str, Sequence[str], None] = '4fe16e04174c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_query_history', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('database_query_history', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('ddl_query_history', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('ddl_query_history', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ddl_query_history', 'duration')
    op.drop_column('ddl_query_history', 'end_date')
    op.drop_column('database_query_history', 'duration')
    op.drop_column('database_query_history', 'end_date')
    # ### end Alembic commands ###
