"""init

Revision ID: 4fe16e04174c
Revises: 
Create Date: 2025-07-17 17:05:18.848645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4fe16e04174c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_query_history',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', mysql.LONGTEXT(), nullable=False),
    sa.Column('response', mysql.LONGTEXT(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', mysql.LONGTEXT(), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.Column('reg_user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_database_query_history_id'), 'database_query_history', ['id'], unique=False)
    op.create_table('ddl_query_history',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('ddl', mysql.LONGTEXT(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', mysql.LONGTEXT(), nullable=False),
    sa.Column('response', mysql.LONGTEXT(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', mysql.LONGTEXT(), nullable=True),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.Column('reg_user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ddl_query_history_id'), 'ddl_query_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ddl_query_history_id'), table_name='ddl_query_history')
    op.drop_table('ddl_query_history')
    op.drop_index(op.f('ix_database_query_history_id'), table_name='database_query_history')
    op.drop_table('database_query_history')
    # ### end Alembic commands ###
