CREATE DATABASE IF NOT EXISTS auth DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS connection DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ddl_session DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS history DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON auth.* TO 'queryme'@'%';
GRANT ALL PRIVILEGES ON connection.* TO 'queryme'@'%';
GRANT ALL PRIVILEGES ON ddl_session.* TO 'queryme'@'%';
GRANT ALL PRIVILEGES ON history.* TO 'queryme'@'%';

FLUSH PRIVILEGES;